export const styles = {
  lane:{
    background: '#e2e4e7', // 浅灰色背景
    width: '360px',
    borderRadius: '8px',
    padding: '12px',
    marginRight: '8px',
    boxShadow: '0 2px 4px rgba(179, 168, 168, 0.05)',
    display: 'flex',
    height: 'fit-content',
    flexDirection: 'column',
    maxHeight: '85vh',
    alignSelf: 'flex-start',
  },
  card: {
    minHeight: '60px',
    background: '#fefeff',
    padding: '16px',
    marginBottom: '18px',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    cursor: 'grab',
    transition: 'all 0.2s ease', // 增加平滑过渡
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    fontSize: '14px',
    color: '#172b4d',
    overflow: 'hidden', // 确保圆角处不会溢出
  },
  addButton: {
    width: '100%',
    padding: '8px',
    marginTop: '4px',
    cursor: 'pointer',
    border: 'none',
    borderRadius: '4px',
    background: 'transparent',
    color: '#5e6c84',
    textAlign: 'left',
    fontSize: '14px',
    transition: 'background 0.2s',
  },
  addLaneBtn: {
    minWidth: '280px',
    height: '50px',
    background: 'rgba(255, 255, 255, 0.2)', // 半透明白
    border: '2px dashed #ffffff',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: '#ffffff',
    fontWeight: 'bold',
    transition: 'background 0.2s',
  },
  deleteBtn: {
    fontSize: '20px', 
    flexShrink: 0, // 强制按钮不被压缩，永远保持原有大小
    border: 'none',
    background: 'none',
    color: '#2b1a4e',
    cursor: 'pointer',
    opacity: 0.6,
    padding: '0 6px',
    borderRadius: '4px',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(23, 43, 77, 0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '16px',
  },
  modalPanel: {
    width: '100%',
    maxWidth: '420px',
    background: '#ffffff',
    borderRadius: '10px',
    padding: '20px',
    boxShadow: '0 12px 32px rgba(0, 0, 0, 0.18)',
  },
  modalTitle: {
    margin: '0 0 16px',
    fontSize: '18px',
    color: '#172b4d',
  },
  modalLabel: {
    display: 'block',
    marginBottom: '6px',
    fontSize: '13px',
    color: '#5e6c84',
  },
  modalInput: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '10px 12px',
    marginBottom: '14px',
    border: '1px solid #dfe1e6',
    borderRadius: '6px',
    fontSize: '14px',
    color: '#172b4d',
    outline: 'none',
  },
  modalTextarea: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '10px 12px',
    marginBottom: '14px',
    border: '1px solid #dfe1e6',
    borderRadius: '6px',
    fontSize: '14px',
    color: '#172b4d',
    outline: 'none',
    minHeight: '96px',
    resize: 'vertical',
    fontFamily: 'inherit',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
    marginTop: '4px',
  },
  modalCancelBtn: {
    padding: '8px 14px',
    border: 'none',
    borderRadius: '6px',
    background: '#ebecf0',
    color: '#172b4d',
    cursor: 'pointer',
    fontSize: '14px',
  },
  modalSubmitBtn: {
    padding: '8px 14px',
    border: 'none',
    borderRadius: '6px',
    background: '#0052cc',
    color: '#ffffff',
    cursor: 'pointer',
    fontSize: '14px',
  },
  appShell: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    minWidth: '100vw',
    backgroundColor: '#b0bece',
  },
  boardRow: {
    display: 'flex',
    padding: '12px 20px 20px',
    gap: '8px',
    alignItems: 'flex-start',
    overflowX: 'auto',
    flex: 1,
  },
  filterBar: {
    margin: '16px 20px 0',
    padding: '14px 16px',
    background: 'rgba(255, 255, 255, 0.92)',
    borderRadius: '10px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  filterRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  filterSearch: {
    flex: 1,
    minWidth: '220px',
    boxSizing: 'border-box',
    padding: '10px 12px',
    border: '1px solid #dfe1e6',
    borderRadius: '6px',
    fontSize: '14px',
    color: '#172b4d',
    outline: 'none',
  },
  filterClearBtn: {
    padding: '8px 12px',
    border: 'none',
    borderRadius: '6px',
    background: '#ebecf0',
    color: '#172b4d',
    cursor: 'pointer',
    fontSize: '13px',
  },
  filterMeta: {
    fontSize: '13px',
    color: '#5e6c84',
    whiteSpace: 'nowrap',
  },
  filterLabel: {
    fontSize: '13px',
    color: '#5e6c84',
    minWidth: '48px',
  },
  filterChips: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    flex: 1,
  },
  filterChip: {
    padding: '6px 10px',
    border: '1px solid #dfe1e6',
    borderRadius: '6px',
    background: '#ffffff',
    color: '#172b4d',
    cursor: 'pointer',
    fontSize: '13px',
  },
  filterChipActive: {
    borderColor: '#0052cc',
    background: '#deebff',
    color: '#0052cc',
  },
  filterEmpty: {
    fontSize: '13px',
    color: '#97a0af',
  },
  tagList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '10px',
  },
  tagChip: {
    padding: '2px 8px',
    borderRadius: '4px',
    background: '#e9f2ff',
    color: '#0052cc',
    fontSize: '12px',
  },
  tagEditHint: {
    marginTop: '10px',
    fontSize: '12px',
    color: '#97a0af',
    cursor: 'pointer',
    borderBottom: '1px dashed #ccc',
    display: 'inline-block',
  },
}